// NWMSP_GetEventHnd
// NWMSP_ReadyEventHnd
// NWMSP_ConnectEventHnd
// NWMSP_DisconnectEventHnd
// NWMSP_BssinfoEventHnd
// NWMSP_CmderrorEventHnd
// NWMSP_RegdomainEventHnd
// NWMSP_PstreamEventHnd
// NWMSP_NeighborEventHnd
// NWMSP_TkipMicerrEventHnd
// NWMSP_ScancompleteEventHnd
// NWMSP_ReportStatisticsEventHnd
// NWMSP_RssiThresholdEventHnd
// NWMSP_ErrorReportEventHnd
// NWMSP_OptRxFrameEventHnd
// NWMSP_ReportRoamTblEventHnd
// NWMSP_ExtensionEventHnd
// NWMSP_CacEventHnd
// NWMSP_SnrThresholdEventHnd
// NWMSP_LqThresholdEventHnd
// NWMSP_TxRetryErrEventHnd
// NWMSP_ReportRoamDataEventHnd
// NWMSP_TestEventHnd
// NWMSP_AplistEventHnd
// NWMSP_GetWowListEventHnd
// NWMSP_CreatePstreamReplyHnd
// NWMSP_DeletePstreamReplyHnd
