// wpadeauth_callback
// wpatx_callback
// wpaconnect_callback
// wparx_callback
// wpadisconnect_callback
// wpa_driver_dragon_event_receive
// wpa_driver_dragon_scan
// wpa_driver_dragon_get_scan_results
// wpa_driver_dragon_set_key
// ar6000_cipher
// wpa_driver_dragon_associate
// wpa_driver_dragon_get_bssid
// wpa_driver_dragon_get_ssid
// wpa_driver_dragon_deauthenticate
// wpa_driver_dragon_disassociate
// wpa_driver_dragon_init
// wpa_driver_dragon_deinit
// wpa_driver_dragon_set_param
// wpa_driver_dragon_get_mac_addr
// wpa_driver_dragon_set_countermeasures
// wpa_driver_dragon_operstate
// nwmwpa_callback
// wpakey_callback
