// wpa_selector_to_bitfield
// rsn_selector_to_bitfield
// wpa_parse_wpa_ie
// wpa_eapol_key_mic
// wpa_eapol_key_send
// wpa_sm_key_request
// wpa_supplicant_parse_ies
// wpa_supplicant_key_neg_complete
// wpa_sm_cancel_auth_timeout
// wpa_supplicant_check_group_cipher
// wpa_supplicant_install_gtk
// wpa_supplicant_gtk_tx_bit_workaround
// wpa_report_ie_mismatch
// wpa_sm_get_state
// wpa_sm_rx_eapol
// wpa_sm_init
// wpa_sm_deinit
// wpa_sm_notify_assoc
// wpa_sm_notify_disassoc
// wpa_sm_set_pmk
// wpa_sm_set_scard_ctx
// wpa_sm_set_config
// wpa_sm_set_own_addr
// wpa_sm_set_ifname
// wpa_sm_set_eapol
// wpa_sm_set_param
// wpa_sm_set_assoc_wpa_ie_default
// wpa_sm_set_assoc_wpa_ie
// wpa_sm_set_ap_wpa_ie
// wpa_sm_set_ap_rsn_ie
// wpa_sm_parse_own_wpa_ie
