// wpa_eapol_set_wep_key
// wpa_drv_set_key
// wpa_supplicant_set_config_blob
// wpa_supplicant_get_config_blob
// wpa_supplicant_set_wpa_none_key
// wpa_list_get
// wpa_blacklist_get
// wpa_blacklist_add
// wpa_blacklist_del
// wpa_blacklist_clear
// wpa_scan_result_compare
// wpa_supplicant_req_scan
// wpa_supplicant_cancel_scan
// wpa_supplicant_timeout
// wpa_supplicant_req_auth_timeout
// wpa_supplicant_cancel_auth_timeout
// wpa_supplicant_initiate_eapol
// wpa_supplicant_set_non_wpa_policy
// wpa_clear_keys
// wpa_drv_mlme_setprotection
// wpa_supplicant_set_state
// wpa_drv_set_operstate
// wpa_supplicant_scan
// cipher_suite2driver
// wpa_supplicant_set_suites
// wpa_supplicant_associate
// wpa_drv_set_mode
// wpa_drv_set_drop_unencrypted
// wpa_drv_get_capa
// wpa_supplicant_disassociate
// wpa_supplicant_deauthenticate
// wpa_supplicant_get_scan_results
// wpa_get_beacon_ie
// wpa_supplicant_get_beacon_ie
// wpa_supplicant_get_ssid
// wpa_drv_get_bssid
// _wpa_alloc_eapol
// _wpa_ether_send
// _wpa_supplicant_req_scan
// _wpa_supplicant_cancel_auth_timeout
// _wpa_supplicant_set_state
// _wpa_supplicant_get_state
// _wpa_supplicant_disassociate
// _wpa_supplicant_deauthenticate
// _wpa_supplicant_get_ssid
// wpa_supplicant_get_bssid
// wpa_supplicant_set_key
// wpa_supplicant_mlme_setprotection
// wpa_supplicant_rx_eapol
// wpa_supplicant_driver_init
// wpa_drv_get_mac_addr
// wpa_drv_set_wpa
// wpa_drv_set_countermeasures
// wpa_supplicant_deinit_iface
// wpa_supplicant_add_iface
// wpa_supplicant_remove_iface
// wpa_supplicant_get_iface
// wpa_supplicant_init
// wpa_supplicant_run
// wpa_supplicant_deinit
